GET http://localhost:3001/api/notes

###

GET http://localhost:3001/api/notes/2

###

POST http://localhost:3001/api/notes
content-Type: application/json

{
    "content": "test01",
    "important": true
}